/**
 * Screenshots of the running application, keyed to the capability they show.
 *
 * SEPARATE FROM capabilities.ts ON PURPOSE. That module is imported by
 * `capabilities.test.ts`, which runs inside workerd via the Cloudflare vitest
 * pool — a runtime with no notion of a PNG import. Putting these `import`
 * statements there turns the drift guard into a module-resolution error, and
 * the drift guard is the thing keeping the marketing copy honest.
 *
 * Every image is regenerated by `npm run screens`, which seeds a local database
 * with invented data and photographs the real UI. They are not mockups, and
 * nothing here is from the alpha team's season.
 *
 * The `w`/`h` are the intrinsic pixel dimensions at 2x. They go on the <img> so
 * the browser reserves the right box before the file arrives, which is what
 * stops the page reflowing under the reader as each one loads.
 */
import boards from './screens/boards.webp';
import decisionLog from './screens/decision-log.webp';
import meetings from './screens/meetings.webp';
import notes from './screens/notes.webp';
import roster from './screens/roster.webp';
import portfolio from './screens/portfolio.webp';
import dashboard from './screens/dashboard.webp';

export interface Screen {
  src: string;
  w: number;
  h: number;
  /** Describes the screen for someone who cannot see it, not the feature. */
  alt: string;
  /** Rendered under the frame. Says what to look at. */
  caption: string;
}

export const SCREENS: Record<string, Screen> = {
  boards: {
    src: boards,
    w: 2560,
    h: 1240,
    alt: 'A Coglin board named Chassis and intake, with tasks in To do, In progress, Blocked and Done columns, each showing an assignee and a due date.',
    caption: 'One board per sub-team, with the season’s other tabs alongside it.',
  },
  'decision-log': {
    src: decisionLog,
    w: 2560,
    h: 1800,
    alt: 'A task dialog for "Rebuild the intake for two samples", showing status, assignee, notes, and a decision log describing three attempts at the intake roller.',
    caption:
      'The decision log. Three attempts at an intake, written down the week they happened.',
  },
  meetings: {
    src: meetings,
    w: 2560,
    h: 1640,
    alt: 'A month calendar for August 2026 with build nights marked on Tuesdays and Thursdays.',
    caption: 'Every meeting in the season on one grid.',
  },
  notes: {
    src: notes,
    w: 2560,
    h: 1360,
    alt: 'The notes screen with a document tree on the left and a rich-text document open, grouped under the meeting it was taken at.',
    caption: 'Notes nest under each other and under the meeting they came from.',
  },
  roster: {
    src: roster,
    w: 2560,
    h: 1440,
    alt: 'A team roster listing students by first name and initial with their sub-teams, alongside coaches and mentors.',
    caption:
      'Students by first name and initial. No student email address is stored.',
  },
  portfolio: {
    src: portfolio,
    w: 2560,
    h: 1440,
    alt: 'The portfolio candidates inbox, listing flagged notes and tasks with a suggested award against each.',
    caption: 'Evidence flagged during the season, waiting to be sorted in March.',
  },
  dashboard: {
    src: dashboard,
    w: 2560,
    h: 1400,
    alt: 'The Coglin dashboard showing season progress, the next meeting, and open items.',
    caption: 'Where the season stands, on the screen you open first.',
  },
};
